name: Test Action

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: 22f3000749@ds.study.iitm.ac.in  # Keep your email here
        run: echo "Hello, world!"
