name: Test Action

on:
  push:
    branches:
      - main  # Change to the branch you want

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use the latest version

      - name: Print Email
        run: echo "Hello, world! My email is 22f3000749@ds.study.iitm.ac.in"
